name: Deploy to GitHub Pages  
  
on:  
  push:  
    branches:  
      - main  
  
jobs:  
  deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v2  
        with:  
          persist-credentials: false  
  
      # 安装和配置 Node.js 或其他必要的依赖（如果需要）  
      # - name: Setup Node.js  
      #   uses: actions/setup-node@v2  
      #   with:  
      #     node-version: '14'  
  
      - name: Install and Build (if needed)  
        # 这里你可以添加任何构建命令，比如 npm install, npm run build 等  
        # 但由于我们直接部署文件夹内容，所以这步可以省略  
        run: echo "Skipping build step as we're deploying raw files"  
  
      - name: Deploy  
        uses: JamesIves/github-pages-deploy-action@v4.2.3  
        with:  
          branch: gh-pages # 要部署到的分支  
          folder: doxygen      # 要部署的文件夹  
          clean: true       # 在部署前清理目标分支
